services:
  paylite-payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: vivvaa/paylite-payment-service
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - .:/app/paylite-payment-service
    environment:
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      - "mysql"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin124@
      MYSQL_DATABASE: paylite_payment_service_db
      MYSQL_USER: paylite_payment_service_user
      MYSQL_PASSWORD: user123@
    networks:
      - backend
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_buffer_pool_size=256M
      - --max_connections=1000

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local